### ISSUE TITLE
Lägg till engelska namn till delarna

### ISSUE THREAD

**Issue by glasseyesnake** [ram97-boop/Syllabus-creator#43]

**Comment by siek5256** [comment]
Har lagt till engName i Course och CoursePart, men har inte pushat det till develop än. Skulle gärna vilja ha mer info om denna issue om det behövs mer.

**Comment by soffik** [comment]
@siek5256 Jag tror att det endast var det som behövdes. Däremot ser jag att det i koden under model-branchen ser ut följande för settern i Course och CoursePart:

public String setEngName() {
		return engName;
}

Gissar att det bara blivit en liten miss, men ska ju va en void och att man skickar med en String som parameter

**Comment by siek5256** [comment]
Okej, fixat och färdigt
