### ISSUE TITLE
Ändra så att alla getters i View returnerar komponenter, inte värden

### ISSUE THREAD

**Issue by glasseyesnake** [ram97-boop/Syllabus-creator#61]

**Comment by glasseyesnake** [comment]
Detta gäller både FirstPanel och getNParts() i CourseContentPanel (om den ska användas)

**Comment by soffik** [comment]
@glasseyesnake Ska vara fixat nu - har däremot inte tagit bort isDistance, gradingScale och thesis i FirstPanel. Men de ser inte ut att behövas längre
