### ISSUE TITLE
Fixa så användare kan byta ordning på kursdelar för sparad kurs

### ISSUE THREAD

**Issue by soffik** [ram97-boop/Syllabus-creator#88]
Just nu sätts kursdelarna till den ordning användaren satte första gången när kursen skapades. Detta borde ändras så man kan byta plats på vilken del som är del 1, del 2 osv.

**Comment by siek5256** [comment]
Har lagt till en ny metod swapCourseParts i course, borde underlätta med denna issue.

**Comment by soffik** [comment]
Jag hade redan fixat det innan du skapade metoden, men om jag har tid så ska jag kolla på om jag kan ändra min kod så jag använder den metoden. Jag låter ärendet vara öppet tillsvidare!

**Comment by soffik** [comment]
Har fixat så metoden du gjort används för att lösa detta issue
